services:
  offering-manager:
    build:
      context: .
      dockerfile: Dockerfile
    image: offering-manager:latest
    container_name: offering-manager
    ports:
      - "8080:8080"
    depends_on:
      postgres-offering-manager:
        condition: service_healthy
    env_file:
      - ./default.env
#    networks:
#      - local-participant-network
    restart: always

  postgres-offering-manager:
    image: postgres:16
    container_name: postgres-offering-manager
    ports:
      - "5432:5432"
    env_file:
      - ./default.env
    volumes:
      - "./postgresdata:/var/lib/postgresql/data:ro=true,U=true"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5